### ISSUE TITLE
[BUG Report] Confirmation with [Y/n] should default to "yes"

### ISSUE THREAD

**Issue by Crocmagnon** [nao1215/gup#146]
## gup version
```console
$ gup version
gup version v0.25.2 (under Apache License version 2.0)
```

## Description (About the problem)
When removing a binary, a confirmation is asked with `[Y/n]`. This syntax is commonly used to denote that "yes" is the default answer when just sending Enter.
`gup` however doesn't do anything when only Enter is sent. It re-asks the same question.

## Steps to reproduce
```console
$ gup remove go1.22.2
gup:CHECK: remove /Users/gaugendre/go/bin/go1.22.2? [Y/n]
gup:CHECK: remove /Users/gaugendre/go/bin/go1.22.2? [Y/n] y
gup:INFO : removed /Users/gaugendre/go/bin/go1.22.2
```

## Expected behavior
Either set a default behavior according to the capitalized choice (preferred), or change the string to read `[y/n]`

**Comment by nao1215** [comment]
@Crocmagnon 
Thank you for writing the bug report.
To be honest, I didn't know about that rule. It has been fixed in PR #147 .
