### ISSUE TITLE
error fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by Darkcast** [nao1215/gup#16]
ran gup update
and got fatal: not a git repository (or any of the parent directories): .git

**Comment by nao1215** [comment]
Hi, @Darkcast 
The bug doesn't reappear.

Please give me the following information.
- Log when an error occurs
- List of binaries under $GOPATH/bin

> fatal: not a git repository (or any of the parent directories): .git

An error may have occurred because git has not been set up.

**Comment by jsumners** [comment]
```
❯ go install github.com/nao1215/gup@latest
go: downloading github.com/nao1215/gup v0.10.3
go: downloading github.com/gen2brain/beeep v0.0.0-20210529141713-5586760f0cc1
go: downloading golang.org/x/sys v0.0.0-20220412211240-33da011f77ad

~ took 2s
❯ gup update
fatal: not a git repository (or any of the parent directories): .git

~
❯ date
Wed May 11 07:45:36 EDT 2022
```

Can't even run `gup --version` without getting the error.

**Comment by nao1215** [comment]
Hi, @jsumners 
Thanks for reporting the bug!

In order to investigate the cause of the bug, I would like to have the following command results from you.
1. `gup list`
2. `ls $GOPATH/bin`

>Can't even run gup --version without getting the error.

gup does not have --version option, only has version subcommand.

**Comment by jsumners** [comment]
```
❯ go install github.com/nao1215/gup@latest

~ took 2s
❯ gup list
fatal: not a git repository (or any of the parent directories): .git

~
❯ ls $GOPATH/bin
addlicense    dlv           go-acc        goimports     goplay        gup           kind          porto
apidiff       ghr           gocovmerge    golangci-lint gopls         impi          misspell      semconvgen
checkdoc      go            gofmt         gomodifytags  gotests       impl          multimod      staticcheck

~
❯
```

**Comment by nao1215** [comment]
Thank you, @jsumners

I checked the code and could not find any error output.
The gup command stops processing when a FATAL error occurs. However, it outputs to standard error in the following format.
```
gup:FATAL: error message. 
```

**Comment by jsumners** [comment]
Sorry, I don't know what you're telling me. As far as I know, `go install` is for installing binaries for tools written in Go, e.g.:

```
~ $ go install github.com/go-task/task/v3/cmd/task@latest
```

The error seems to indicate that `gup` only works inside of a local Go project that has a `.git` directory.

**Comment by nao1215** [comment]
>The error seems to indicate that gup only works inside of a local Go project that has a .git directory.

If you run the gup command in your local git project (anything is OK), does the gup command work correctly?
I really don't know what caused the bug...

**Comment by jsumners** [comment]
> Is it possible that you are running a different command named gup?

That's it! The oh-my-zsh git aliases conflict. Running `\gup` to skip the alias works as advertised.

**Comment by nao1215** [comment]
@jsumners 
Thank you for the bug report.
I have written about this bug in the README. 
I'd be happy to see fewer people facing similar problems.
