### ISSUE TITLE
Integrate completions into Homebrew formula

### ISSUE THREAD

**Issue by trallnag** [nao1215/gup#168]
## Is your feature request related to a problem?

Currently completions are not part of formula and have to be set up seperately.

Note that it is not really a problem for me. Just an idea for improvement.

## Describe the solution you'd like

Integrate completions into Homebrew formula

## Additional context

Homebrew supports completions in formulae.

Goreleaser supports completions. It is described well in this article: <https://carlosbecker.com/posts/golang-completions-cobra/>

**Comment by nao1215** [comment]
@trallnag 
Thank you for your suggestion.
The feature you suggested has been introduced in v0.27.4

**Comment by trallnag** [comment]
nice, thank you
