### ISSUE TITLE
Don't generate shell completion files by default

### ISSUE THREAD

**Issue by Akimon658** [nao1215/gup#28]
gup is a very simple command, so I don't think all users need shell completion files. Also, Cobra has [`completion` subcommand support](https://github.com/spf13/cobra/blob/master/shell_completions.md) even for PowerShell, and it would be enough for most use cases.
Is there any reason to [disable Cobra's feature](https://github.com/nao1215/gup/blob/3b69ebd1a8fd092fdf970b19facb3991671964df/cmd/root.go#L21) and re-implement similar feature? Even if yes, I think it should be optional.

**Comment by nao1215** [comment]
Hi, @Akimon658
Thank you for your comment.

>gup is a very simple command, so I don't think all users need shell completion files.

I think that gup comman is **not** simple.
gup command has many sub-commans. Each subcommand has options.

I also think that shell completion files are provided by the developer, whether the user uses them or not. Also, if the user does not have knowledge of shell completion files, it is difficult to prompt the user to execute the completion subcommand.

>Cobra has [completion subcommand support](https://github.com/spf13/cobra/blob/master/shell_completions.md) even for PowerShell, and it would be enough for most use cases.

Cobra's `completion` subcommand (default) outputs shell completion text to **standard output**, not files.
I don't remember where I should put my shell completion file. What about other users? Some may not remember.
However, it is easy to generate shell completion files by customizing the `completion` subcommand based on the current implementation.

>Even if yes, I think it should be optional.

I see no difference between a package manager automatically installing shell completion files.
However, after listening to your opinion, I thought that "generating shell completion files for bash, zsh, and fish for Windows users" was undesirable. So, I added [the implementation that does not create shell completion files for Windows users](https://github.com/nao1215/gup/commit/f0b044e18297ac7ae693cf666443f191e3c7a808).

P.S.
The current problem is that PowerShell shell completion files are not generated. I am not familiar with Windows (moreover, I don't have Winows), so implementation is a low priority.

**Comment by Akimon658** [comment]
OK, I understand. Thank you so much!
