### ISSUE TITLE
Add option to disable notification

### ISSUE THREAD

**Issue by giggio** [nao1215/gup#56]
## What

I'd like to have a flag to disable notifications. I don't need them and it warns everytime with `gup:WARN : exec: "notify-send": executable file not found in $PATH`.

## How

I'm thinking of something like `gup update --no-notification` (I'm fine with any other flag).

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by nao1215** [comment]
@giggio 
Thank you for the suggestion.
I would like to add an option to enable notifications (-N, --notify) and disable them by default.

**Comment by giggio** [comment]
I'd prefer that. I didn't suggest because I thought you had a reason to have it on by default.

**Comment by nao1215** [comment]
I write down PR #57.
I will merge when I add the unit tests.

**Comment by nao1215** [comment]
@giggio 
The feature you wanted was introduced in [v0.15.0 (newest version)](https://github.com/nao1215/gup/releases/tag/v0.15.0).
I close this issue.
