### ISSUE TITLE
question: how to set default ldflags

### ISSUE THREAD

**Issue by phanirithvij** [nao1215/gup#66]
I would like to use `go install -ldflags='-w -s' pkgurl@ver` for everything, this reduces binary sizes in GOBIN by ~ 30% (overall).

Is there a way to set those when using gup? Like when `gup update pkg`, then gup should use those ldflags?

<details>
<summary>Looks like go install doesn't respect <code>LDFLAGS</code> unless passed as <code>go install -ldflags='-w -s'</code>.</summary>

I've tried the environment vars, `LDFLAGS`, `GO_LDFLAGS` and `CGO_LDFLAGS` like so (not sure which, so tried all of them, none stripped the file)

```shell
LDFLAGS="-w -s" go install -v github.com/jesseduffield/lazygit@latest
GO_LDFLAGS="-w -s" go install -v github.com/jesseduffield/lazygit@latest
CGO_LDFLAGS="-w -s" go install -v github.com/jesseduffield/lazygit@latest
```
But the file is not stripped, has debug info (in all three cases)
```shell
$ file ~/go/bin/lazygit
/data/data/com.termux/files/home/go/bin/lazygit: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, Go BuildID=LLfEyEXjEMrHvyjZonKj/4Fhy_N4CI4C1iqkyYndi/Bccr-D0Pj5lrRwMW3oUo/YAQMGE7PR-yDhkUxbTdR, with debug_info, not stripped
```
whereas with `go install -ldflags='-w -s'`
```shell
$ file ~/go/bin/lazygit
/data/data/com.termux/files/home/go/bin/lazygit: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, Go BuildID=CRHRVUhGdkG5b7WqnThF/qtUCSK8Z1bQhyb1zl3GH/Bccr-D0Pj5lrRwMW3oUo/lbWf2uesZwgNtp_3y9lt, stripped
```

On side note, `CGO_LDFLAGS` does strip when using `go build` but not go install whereas -ldflags arg is the only one that works for both go install, build.
</details>

**Comment by nao1215** [comment]
@phanirithvij 
Thank you for your comment.
gup does not support ldflags; an implementation is needed to support ldflags.

**Comment by nao1215** [comment]
NOTE: need to change this code.
https://github.com/nao1215/gup/blob/ce661c54b351226619927decc90660aaa8217fdf/internal/goutil/goutil.go#L189-L204

**Comment by phanirithvij** [comment]
Found a way to do it with environment vars
```shell
# for a reproducible build
GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-s" gup update
# or just
GOFLAGS="-ldflags=-s" gup update
```
- `-w` doesn't seem to be doing anything when -s is used. (tried it and Go BuildID obtained from file command is same with or without -w when using along with -s)
- Another alternate is to just use the linux `strip` command. `strip $GOBIN/*`
- refer: 
	- https://github.com/golang/go/issues/32782#issuecomment-505679408
	- https://github.com/golang/go/issues/33581
	- https://github.com/archlinuxcn/repo/blob/d77acc5bacc0916b8fceeb98c055734f24c5eedb/archlinuxcn/tidb/PKGBUILD#L45

**Comment by phanirithvij** [comment]
- As for whether or not gup should have ldflags, I think it would be helpful, when complex ldflags like for e.g. `-X pkg/path.VersionX ... -X ...` are needed
- but not sure if people using `gup update` are expecting any such behavior other than just cli binaries getting updated.
