### ISSUE TITLE
Support XDG_CONFIG_HOME for configuration files path

### ISSUE THREAD

**Issue by ralish** [nao1215/gup#67]
**Describe the bug**
The configuration base directory is hardcoded to `$HOME/.config`. This is a reasonable fallback, but ideally it would respect the `XDG_CONFIG_HOME` environment variable as specified in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

> $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

**To Reproduce**
Simply invoke `gup` and the `$HOME/.config/gup` directory will be created, including the parent `$HOME/.config` directory if it doesn't exist. This occurs even if `$XDG_CONFIG_HOME` is set and specifies a different path for program configuration data.

**Expected behavior**
Respect `$XDG_CONFIG_HOME` if it's set and usable (writeable directory or we can create one at the location). If it's not set, or there's a failure of some form, fallback to `$HOME/.config`. A warning specifying what went wrong should be printed if `$XDG_CONFIG_HOME` is set but we're unable to use it for some reason.

**Desktop (please complete the following information):**
 - OS: Windows 11 (but the specification is cross-platform)
 - Go Version: 1.19.5
 - Application Version: 0.15.1

**Comment by nao1215** [comment]
@ralish 
Thanks for reporting the bug.
I have known about $XDG_CONFIG_HOME since I started implementing gup. However, I did not adopt it because it was an environment variable with which I was not familiar.

Now that more users are using gup, I will try to follow the standard specifications as much as possible.
See this PR #68

**Comment by ralish** [comment]
@nao1215 That's awesome, thanks for implementing that so fast. I've just tested it myself and it's working as expected.
