### ISSUE TITLE
make generation of completion configurable

### ISSUE THREAD

**Issue by jlec** [nao1215/gup#72]
I really like the idea to promote the use of shell completions and enhance the user experience. but please make it a bit more configurable.

I am using `~/.bash_completions.d/gup.conf` in preference over a massive `~/.bash_completion` file.

Could we either have a switch for the generation of the completions or have the location be configurable?

**Comment by nao1215** [comment]
@jlec 
Thank you for your comment.
I have fixed the gup command a bit, although not quite what you want.

Please check PR #73 .

**Comment by jlec** [comment]
@nao1215 Nice work. LGTM
